<!DOCTYPE html>
<html lang="en-us">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Deferred Cleanup, Checking Errors, and Potential Problems -- Bleve</title>

    

    <link href="https://www.blevesearch.com//img/favicon.ico" rel="icon">

    
    <link href="https://www.blevesearch.com//css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://www.blevesearch.com//css/font-awesome.min.css">

    
    <link rel="stylesheet" href="https://www.blevesearch.com//css/prism.css"/>

    
    <link href="https://www.blevesearch.com//css/bleve.css" rel="stylesheet">

    
    
    

</head>

<body>

    <div class="container">
        
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                
                <div class="navbar-header page-scroll">
                    <a href="/"><img class="logo" src="https://www.blevesearch.com//img/bleve-icon-placard-small.png"/></a>
                    <a class="navbar-brand" href="/">Bleve</a>
                </div>

                           
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              
                <ul class="nav navbar-nav navbar-right">
                    
                    <li  >
                        <a href="/docs/Home/">Documentation</a>
                    </li>
                    
                    <li  >
                        <a href="/videos/">Videos</a>
                    </li>
                    
                    <li  >
                        <a href="/community/">Community</a>
                    </li>
                    
                    <li  >
                        <a href="/news/">News</a>
                    </li>
                    
                    <li  >
                        <a href="/events/">Events</a>
                    </li>
                    
                    <li  >
                        <a href="https://github.com/blevesearch/bleve">Code</a>
                    </li>
                    

                    <div class="dropdown pull-right">
                      <form class="navbar-form" role="search" action="/search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search" name="q" id="srch-term">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                      </form>
                    </div>

                  </ul>
            </div>
           

            </div>
            
        </nav>

<div class="row">
    <div class="col-lg-9 docmain">
    	<h1>Deferred Cleanup, Checking Errors, and Potential Problems</h1>

		

<p>The <em>defer</em> statement in Go is frequently used to ensure that once a resource has been acquired, it will be properly cleaned up.  In its simplest form it works exactly as you expect.  But, as you move to more advanced usages there are some things to watch out for.  I&rsquo;d like to share one that I recently ran into while writing Bleve test cases.</p>

<h3 id="basics:ffe76477ce26feb5927595f82ec07acf">Basics</h3>

<p>The power of the <em>defer</em> statement in Go is that it lets you put the acquisition and cleanup of a resource side by side.  When you read code later, it&rsquo;s easy to see that the correct behavior is guaranteed.  Let&rsquo;s take a look at a simple example:</p>

<pre><code>func main() {
	r, err := Open(&quot;a&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'a'\n&quot;)
	}
	defer r.Close()
}

type Resource struct {
	name string
}

func Open(name string) (*Resource, error) {
	return &amp;Resource{name}, nil
}

func (r *Resource) Close() error {
	log.Printf(&quot;closing %s\n&quot;, r.name)
	return nil
}
</code></pre>

<p><a href="http://play.golang.org/p/fYB2alVcIw">Run this in the Go Playground</a></p>

<p>The main function shows some very common behavior.  Open a resource, check for an error, then <em>defer</em> Closing the resource.  When we run this, we get the expected behavior:</p>

<pre><code>2009/11/10 23:00:00 closing a
</code></pre>

<h3 id="opening-another-resource-reusing-the-variable:ffe76477ce26feb5927595f82ec07acf">Opening another Resource, Reusing the Variable</h3>

<p>Let&rsquo;s make the example a bit more complex.  Now, after closing the resource, we will open another one (with a different name).  Can we reuse the same variable?</p>

<pre><code>func main() {
	r, err := Open(&quot;a&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'a'\n&quot;)
	}
	defer r.Close()

	r, err = Open(&quot;b&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'b'\n&quot;)
	}
	defer r.Close()
}
</code></pre>

<p><a href="http://play.golang.org/p/Bal_y0nv4U">Run this in the Go Playground</a></p>

<p>When I was new to Go and first encountered this code I wasn&rsquo;t sure if this would work.  I knew that <em>defer</em> would not execute until the end of main, but would it close &lsquo;a&rsquo; AND &lsquo;b&rsquo;?  Or would it close &lsquo;b&rsquo; twice?  If we run it we see:</p>

<pre><code>2009/11/10 23:00:00 closing b
2009/11/10 23:00:00 closing a
</code></pre>

<p>So, it does work, this is the expected output.  Some of you may be wondering, but <em>why</em> does it work?  As the Go blog <a href="http://blog.golang.org/defer-panic-and-recover">Defer, Panic, and Recover</a> explains,</p>

<blockquote>
<p>&ldquo;A deferred function&rsquo;s arguments are evaluated when the defer statement is evaluated.&rdquo;</p>
</blockquote>

<p>In our case, the method receiver &lsquo;r&rsquo; for the Close() method behaves just like an argument.  So the &lsquo;r&rsquo; is evaluated at the time the defer statement is evaluated, and <em>NOT</em> when the statement is executed.  In Bleve code we saw this pattern occur frequently in test cases.  We would acquire a resource, take some action, close the resource, check the state of things, then repeat the process.</p>

<h3 id="errcheck:ffe76477ce26feb5927595f82ec07acf">errcheck?</h3>

<p>Last February I had the amazing opportunity to attend <a href="http://www.gophercon.in/">GopherCon India</a>.  One of the many things I learned while there was of a tool called <a href="https://github.com/kisielk/errcheck">errcheck</a>.  The idea of the tool is simple, it looks at your Go code and identifies places where you&rsquo;re not checking a returned error.  This seemed like such an obvious thing to do, so I ran it on the entire Bleve codebase.  We found several clear cases where an error was returned, and we would not propagate the error back to the caller.</p>

<p>But what happens if we run <em>errcheck</em> on the code we just wrote above?</p>

<pre><code>github.com/mschoch/defertest/main.go:10:15	defer r.Close()
github.com/mschoch/defertest/main.go:16:15	defer r.Close()
</code></pre>

<p>The Close() method returns an error.  Although it&rsquo;s not used in this contrived example, I coded it that way on purpose as that is very common in the real world.  Does checking this error matter?  If closing the first resource results in an error, should you try to close the second one?  In the abstract these are interesting philosophical questions, but let&rsquo;s assume we do want to check the errors.  How would we do it?  My first attempt looked like this:</p>

<pre><code>func main() {
	r, err := Open(&quot;a&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'a'\n&quot;)
	}
	defer func() {
		err := r.Close()
		if err != nil {
			log.Fatal(err)
		}
	}()

	r, err = Open(&quot;b&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'b'\n&quot;)
	}
	defer func() {
		err := r.Close()
		if err != nil {
			log.Fatal(err)
		}
	}()
}
</code></pre>

<p><a href="http://play.golang.org/p/_MPUl6zWjF">Run this in the Go Playground</a></p>

<p>I added an anonymous function which invokes r.Close(), checks the error, and if its non-nil we exit the program through log.Fatal().  It seems like such a simple change, but we&rsquo;ve introduced a severe bug into the code.  In our case we can see it clearly since we&rsquo;re printing out the name of the resource being closed:</p>

<pre><code>2009/11/10 23:00:00 closing b
2009/11/10 23:00:00 closing b
</code></pre>

<p>Oops!  We&rsquo;re now closing the &lsquo;b&rsquo; resource twice, and never closing the &lsquo;a&rsquo; resource.  This is a severe problem, closing &lsquo;b&rsquo; a second time may not be well defined behavior, and not closing &lsquo;a&rsquo; may leak resources.</p>

<p>Where did we go wrong?  Remember the rule we were given was:</p>

<blockquote>
<p>&ldquo;A deferred function&rsquo;s arguments are evaluated when the defer statement is evaluated.&rdquo;</p>
</blockquote>

<p>And in our new code, the deferred function has no arguments, and no method receiver.  We&rsquo;re now relying the anonymous function referring to &lsquo;r&rsquo;.  The Go spec says:</p>

<blockquote>
<p>&rdquo;&hellip;they may refer to variables defined in a surrounding function. Those variables are then shared between the surrounding function and the function literal, and they survive as long as they are accessible.&rdquo;</p>
</blockquote>

<p>So, now it&rsquo;s fairly clear what happened.  At the time the <em>defer</em> statement was evaluated, the arguments were evaluated, but there were none.  Then at the end of the function, the deferred function is executed, and <em>now</em> as the anonymous functions are executed, &lsquo;r&rsquo; is evaluated, and in both cases it refers to &lsquo;b&rsquo;.</p>

<h3 id="the-fix:ffe76477ce26feb5927595f82ec07acf">The Fix</h3>

<p>Option 1, we can rewrite the <em>defer</em> statement to pass &lsquo;r&rsquo; as an argument:</p>

<pre><code>func main() {
	r, err := Open(&quot;a&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'a'\n&quot;)
	}
	defer func(r *Resource) {
		err := r.Close()
		if err != nil {
			log.Fatal(err)
		}
	}(r)

	r, err = Open(&quot;b&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'b'\n&quot;)
	}
	defer func(r *Resource) {
		err := r.Close()
		if err != nil {
			log.Fatal(err)
		}
	}(r)
}
</code></pre>

<p>This does give the correct output:</p>

<pre><code>2009/11/10 23:00:00 closing b
2009/11/10 23:00:00 closing a
</code></pre>

<p>But, to be honest, it&rsquo;s rather verbose.  In many cases it may just be simpler to use a different variable name.  Option 2, use a new variable for the second resource:</p>

<pre><code>func main() {
	r, err := Open(&quot;a&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'a'\n&quot;)
	}
	defer func() {
		err := r.Close()
		if err != nil {
			log.Fatal(err)
		}
	}()

	r2, err := Open(&quot;b&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'b'\n&quot;)
	}
	defer func() {
		err := r2.Close()
		if err != nil {
			log.Fatal(err)
		}
	}()
}
</code></pre>

<p><strong>UPDATE: 2015-09-29</strong></p>

<p>Users <a href="https://www.reddit.com/r/golang/comments/3mqxar/deferred_cleanup_checking_errors_and_potential/">discussing this on Reddit</a> proposed a third option.  Create a named cleanup function and use the existing io.Closer interface:</p>

<pre><code>func main() {
	r, err := Open(&quot;a&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'a'\n&quot;)
	}
	defer Close(r)

	r, err = Open(&quot;b&quot;)
	if err != nil {
		log.Fatalf(&quot;error opening 'b'\n&quot;)
	}
	defer Close(r)
}

func Close(c io.Closer) {
	err := c.Close()
	if err != nil {
		log.Fatal(err)
	}
}
</code></pre>

<p><a href="http://play.golang.org/p/ZjlavK1r6N">Run this in the Go Playground</a></p>

<p>As I mentioned earlier, in Bleve this pattern only seems to arise in test cases.  I suspect in real code you&rsquo;d be more likely to already be using more descriptive identifiers.</p>

<h3 id="summary:ffe76477ce26feb5927595f82ec07acf">Summary</h3>

<p>To me the lesson here is that we had a simple pattern for deferred cleanup that worked.  I even explicitly took the time to verify that it cleaned up the correct resources when I reused variables.  Then I took the seemingly natural step to make sure we check all the returned errors.  But, I was a bit careless and overlooked that the deferred anonymous function can have significantly different behavior.  It wasn&rsquo;t until I observed problems that I went back to recheck my assumptions and track down the problem.</p>

	</div>

    <div class="col-lg-3">

    	

    </div>


</div>

      <hr>
      
      <footer>
          <div class="container">
              <div class="row">
                  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                      <li>
                        <a href="mailto:info@blevesearch.com">
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-envelope-o fa-stack-1x fa-inverse"></i>
                          </span>
                        </a>
                      </li>
                      
                      <li>
                        <a href="https://twitter.com/blevesearch">
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                          </span>
                        </a>
                      </li>
                      
                      <li>
                        <a href="https://github.com/blevesearch">
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                          </span>
                        </a>
                      </li>
                      
                    </ul>
                    <p class="copyright">Site built with <img class="icon" src="/img/hugo.png"/> <a href="http://gohugo.io/">Hugo</a>.  Search powered by <img class="icon" src="/img/bleve-icon-placard-small.png"/> <a href="http://www.blevesearch.com/">Bleve</a>.</p>
                    <p class="copyright text-muted">© <a href="http://couchbase.com/">Couchbase</a> 2015-2018</p>
                  </div>
              </div>
          </div>
      </footer>
    </div>

    
    <script src="https://www.blevesearch.com//js/jquery.min.js"></script>

    
    <script src="https://www.blevesearch.com//js/bootstrap.min.js"></script>

    <script src="https://www.blevesearch.com//js/prism.js"></script>

    <script src="/js/handlebars.js"></script>
    <script src="/js/search.js"></script>

    
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-54278444-1', 'auto');
  ga('send', 'pageview');
</script>

</body>

</html>

